version: "3.8"
services:
  user-rest-api:
    build: .
    ports:
      - "8083:8084"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=8084
  postgres-spring:
    image: postgres
    ports:
      - "2022:5432"
    environment:
      - POSTGRES_PASSWORD=admin